Some modals don't have modal content
This is causing an error to appear sometimes:
TypeError: Cannot read property 'addEventListener' of null

Checking for element existence before adding listener